/* ============================================
   GSP TRADING - CANADIAN INVESTOR TAX PACK

   Assembles the year-end tax package a filer or accountant actually acts
   on, out of the tracker's existing plumbing. Two halves:

     1. buildTaxPack(...) -> a structured DATA MODEL (Schedule 3
        dispositions, an income summary, a T5008 reconciliation worksheet
        with a deliberately blank broker column, an optional True Cost
        section from the Fee X-Ray, and an approximate-cost-basis warning
        list). Composes services/tax-report.js and services/fee-xray.js.

     2. renderTaxPackHtml(pack) -> a self-contained, print-ready HTML
        FRAGMENT (light/print palette) suitable for opening in a window
        and printing to PDF.

   HONESTY GUARANTEES
   ------------------
   - This is an educational summary, NOT tax advice, NOT an official CRA
     form, NOT a T-slip. The renderer says so prominently.
   - The module never calls Date(); meta.generatedAt is left null for the
     caller to stamp, so the pure logic stays deterministic and testable.
   - Rows that rest on imported broker averages or estimated FX are
     surfaced so the filer knows exactly what to backfill before filing.
   ============================================ */

'use strict';

const TaxPack = (function () {
  const isNode = (typeof module !== 'undefined' && module.exports);
  const taxReportLib = isNode ? require('./tax-report.js') : (typeof TaxReport !== 'undefined' ? TaxReport : null);
  const feeXrayLib = isNode ? require('./fee-xray.js') : (typeof FeeXray !== 'undefined' ? FeeXray : null);

  function num(v) { const n = Number(v); return isFinite(n) ? n : 0; }
  function round2(v) { const r = Math.round(num(v) * 100) / 100; return r === 0 ? 0 : r; }
  function yearOf(dateISO) { return String(dateISO || '').slice(0, 4); }

  const DISCLAIMER =
    'This is an educational summary generated by GSP Trading from the transactions you entered. ' +
    'It is not tax advice, not an official CRA form, and not a T-slip (T5008, T3, or T5). ' +
    'Verify every figure against your broker slips and confirm with a qualified tax professional before filing.';

  const CAVEATS = [
    'CRA pools identical property across ALL of your accounts and those of affiliated persons (spouse, controlled corporations). This summary sees only the transactions entered in this tracker.',
    'Holdings at other institutions are not included and can change your adjusted cost base and superficial-loss outcomes.',
    'Registered accounts (TFSA, RRSP, FHSA, RESP) are excluded from Schedule 3 by design: gains there are not taxable and losses are not deductible.',
    'Return of capital depends on each fund\'s CDS-published ROC factors. Verify T3 and T5 box amounts before relying on the adjusted cost base shown here.',
    'Foreign income and foreign tax withheld may require the T2209 foreign tax credit and are not computed here.',
    'Amounts flagged approximate rest on imported broker averages or estimated FX and must be backfilled with real trade history before filing.',
  ];

  // Group this year's income entries by symbol, summing amountCad.
  function buildIncomeSummary(income, year) {
    const y = year != null ? String(year) : null;
    const acc = {};
    let grand = 0;
    (Array.isArray(income) ? income : []).forEach(function (e) {
      if (!e) return;
      if (y && yearOf(e.date) !== y) return;
      const sym = e.symbol || '(unknown)';
      const cad = num(e.amountCad);
      acc[sym] = (acc[sym] || 0) + cad;
      grand += cad;
    });
    const bySymbol = Object.keys(acc).sort().map(function (sym) {
      return { symbol: sym, cad: round2(acc[sym]) };
    });
    return { year: y, bySymbol: bySymbol, grandTotalCad: round2(grand) };
  }

  // One reconciliation row per DISPOSED symbol (sell rows only). The broker's
  // T5008 book value and the resulting variance are intentionally left blank
  // for the filer to complete against the actual slip.
  function buildReconciliation(rows) {
    const acc = {};
    (Array.isArray(rows) ? rows : []).forEach(function (r) {
      if (!r || r.type !== 'sell') return;
      const a = acc[r.symbol] || (acc[r.symbol] = { proceeds: 0, acb: 0, gain: 0 });
      a.proceeds += num(r.proceedsCad);
      a.acb += num(r.acbCad);
      a.gain += num(r.gainCad);
    });
    return Object.keys(acc).sort().map(function (sym) {
      const a = acc[sym];
      return {
        symbol: sym,
        trackerProceedsCad: round2(a.proceeds),
        trackerAcbCad: round2(a.acb),
        trackerGainCad: round2(a.gain),
        t5008BookValue: null,   // filer enters the broker's box 20 figure here
        variance: null,         // = t5008BookValue - trackerAcbCad, once entered
        note: 'Enter the broker T5008 cost/book value (box 20) and compare to this tracker ACB. Broker book values are frequently their own average and often wrong; the tracker figure reflects CRA pooling across your taxable accounts.',
      };
    });
  }

  // Optional: the Fee X-Ray "True Cost" story. Built only when both a
  // holdings snapshot and fee inputs are supplied.
  function buildTrueCost(holdings, feeInputs, currentBrokerId) {
    if (!feeXrayLib) return null;
    if (!Array.isArray(holdings) || holdings.length === 0) return null;
    if (feeInputs == null || typeof feeInputs !== 'object') return null;

    const profile = feeXrayLib.buildProfile(holdings, feeInputs);
    const comparison = feeXrayLib.compareAnnualCosts(profile);
    const cheapest = comparison.length ? comparison[0] : null;

    let currentRow = null;
    let fxDrag = null;
    if (currentBrokerId) {
      currentRow = comparison.filter(function (r) { return r.broker === currentBrokerId; })[0] || null;
      const story = feeXrayLib.fxStory(profile, currentBrokerId);
      fxDrag = story.dragAtBroker;
    }

    return {
      currentBrokerId: currentBrokerId || null,
      currentBrokerCost: currentRow ? currentRow.totalYr : null,
      cheapestBrokerCost: cheapest ? cheapest.totalYr : null,
      cheapestBrokerName: cheapest ? cheapest.brokerName : null,
      annualOverpayment: (currentRow && cheapest) ? round2(currentRow.totalYr - cheapest.totalYr) : null,
      fxDrag: fxDrag,
    };
  }

  // buildTaxPack
  //   { positions, income, year, holdings, feeInputs, currentBrokerId }
  function buildTaxPack(arg) {
    if (!taxReportLib) throw new Error('tax-report.js not loaded');
    arg = arg || {};
    const year = arg.year != null ? String(arg.year) : null;

    const rows = taxReportLib.buildDispositions(arg.positions || [], { year: year });
    const summary = taxReportLib.summarize(rows);

    const approxSet = {};
    rows.forEach(function (r) { if (r.approx) approxSet[r.symbol] = true; });
    const approxWarnings = Object.keys(approxSet).sort();

    return {
      meta: {
        year: year,
        generatedAt: null,          // parent stamps this; module never calls Date()
        disclaimer: DISCLAIMER,
        caveats: CAVEATS.slice(),
      },
      schedule3: { rows: rows, summary: summary },
      incomeSummary: buildIncomeSummary(arg.income || [], year),
      reconciliation: buildReconciliation(rows),
      trueCost: buildTrueCost(arg.holdings, arg.feeInputs, arg.currentBrokerId),
      approxWarnings: approxWarnings,
    };
  }

  /* ---------- HTML rendering ---------- */

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  function fmtCad(v) {
    const n = num(v);
    const abs = Math.abs(n).toLocaleString('en-CA', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    return n < 0 ? '(' + '$' + abs + ')' : '$' + abs;
  }

  function fmtShares(v) {
    const n = num(v);
    return n ? n.toLocaleString('en-CA') : '';
  }

  const STYLE = [
    '.gsp-taxpack{--bg:#FBFAF7;--surface:#FFFFFF;--ink:#14181F;--mute:#4A5060;--dim:#7A818E;--bronze:#8A6A2A;--line:#E4DED2;--pos:#1E6B45;--neg:#9A2A2A;',
    'background:var(--bg);color:var(--ink);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Inter,Roboto,Helvetica,Arial,sans-serif;',
    'font-size:12px;line-height:1.5;padding:28px 32px;max-width:1040px;margin:0 auto;box-sizing:border-box;}',
    '.gsp-taxpack *{box-sizing:border-box;}',
    '.gsp-taxpack h1{font-size:24px;font-weight:800;letter-spacing:-0.01em;margin:0 0 2px;}',
    '.gsp-taxpack h2{font-size:14px;font-weight:700;letter-spacing:0.04em;text-transform:uppercase;color:var(--bronze);margin:28px 0 10px;padding-bottom:6px;border-bottom:1px solid var(--line);}',
    '.gsp-taxpack .sub{color:var(--dim);font-size:11px;margin:0 0 4px;}',
    '.gsp-taxpack .disclaimer{margin:16px 0 4px;padding:12px 14px;background:#FBF3E4;border:1px solid var(--bronze);border-left-width:4px;border-radius:4px;}',
    '.gsp-taxpack .disclaimer strong{display:block;font-size:12.5px;color:var(--bronze);letter-spacing:0.02em;margin-bottom:3px;}',
    '.gsp-taxpack .disclaimer p{margin:0;color:var(--mute);font-size:11px;}',
    '.gsp-taxpack table{width:100%;border-collapse:collapse;margin-top:6px;font-variant-numeric:tabular-nums;}',
    '.gsp-taxpack th{text-align:left;font-size:10px;font-weight:700;letter-spacing:0.04em;text-transform:uppercase;color:var(--dim);border-bottom:1.5px solid var(--ink);padding:6px 8px;}',
    '.gsp-taxpack td{padding:6px 8px;border-bottom:1px solid var(--line);vertical-align:top;}',
    '.gsp-taxpack td.num,.gsp-taxpack th.num{text-align:right;}',
    '.gsp-taxpack tr.total td{font-weight:700;border-top:1.5px solid var(--ink);border-bottom:none;background:#F6F2E9;}',
    '.gsp-taxpack .neg{color:var(--neg);}',
    '.gsp-taxpack .pos{color:var(--pos);}',
    '.gsp-taxpack .flag{display:inline-block;font-size:9.5px;font-weight:700;letter-spacing:0.03em;text-transform:uppercase;color:var(--bronze);}',
    '.gsp-taxpack td.blank{background:repeating-linear-gradient(-45deg,#F3EEE4,#F3EEE4 5px,#FBFAF7 5px,#FBFAF7 10px);border:1px dashed var(--dim);min-width:110px;}',
    '.gsp-taxpack .cards{display:flex;flex-wrap:wrap;gap:12px;margin-top:6px;}',
    '.gsp-taxpack .card{flex:1 1 180px;background:var(--surface);border:1px solid var(--line);border-radius:6px;padding:12px 14px;}',
    '.gsp-taxpack .card .k{font-size:10px;letter-spacing:0.04em;text-transform:uppercase;color:var(--dim);margin-bottom:4px;}',
    '.gsp-taxpack .card .v{font-size:18px;font-weight:800;}',
    '.gsp-taxpack .card.hot{border-color:var(--bronze);background:#FBF3E4;}',
    '.gsp-taxpack .card.hot .v{color:var(--bronze);}',
    '.gsp-taxpack .callout{margin-top:6px;padding:10px 14px;background:var(--surface);border:1px solid var(--line);border-left:4px solid var(--bronze);border-radius:4px;font-size:11px;color:var(--mute);}',
    '.gsp-taxpack .callout .chips{margin-top:6px;}',
    '.gsp-taxpack .chip{display:inline-block;margin:2px 4px 2px 0;padding:2px 8px;border:1px solid var(--bronze);border-radius:999px;font-size:10.5px;font-weight:600;color:var(--bronze);}',
    '.gsp-taxpack ul.caveats{margin:6px 0 0;padding-left:18px;color:var(--mute);font-size:11px;}',
    '.gsp-taxpack ul.caveats li{margin:0 0 5px;}',
    '.gsp-taxpack .foot{margin-top:26px;padding-top:10px;border-top:1px solid var(--line);color:var(--dim);font-size:10px;}',
    '@media print{.gsp-taxpack{padding:0;font-size:11px;}.gsp-taxpack h2{page-break-after:avoid;}.gsp-taxpack table{page-break-inside:auto;}.gsp-taxpack tr{page-break-inside:avoid;}}',
  ].join('\n');

  function gainClass(v) { return num(v) < 0 ? ' class="num neg"' : ' class="num pos"'; }

  function renderSchedule3(sch) {
    const rows = (sch && sch.rows) || [];
    const s = (sch && sch.summary) || {};
    let body = '';
    if (!rows.length) {
      body = '<tr><td colspan="7" style="color:#7A818E;padding:12px 8px;">No taxable dispositions recorded for this year.</td></tr>';
    } else {
      rows.forEach(function (r) {
        const label = r.type === 'roc-excess' ? ' <span class="flag">ROC over ACB</span>' : '';
        const flags = [];
        if (r.superficialLoss) flags.push('<span class="flag">Superficial loss denied</span>');
        if (r.approx) flags.push('<span class="flag">Approx</span>');
        body +=
          '<tr>' +
          '<td>' + esc(r.symbol) + label + '</td>' +
          '<td>' + esc(r.date) + '</td>' +
          '<td class="num">' + esc(fmtShares(r.shares)) + '</td>' +
          '<td class="num">' + esc(fmtCad(r.proceedsCad)) + '</td>' +
          '<td class="num">' + esc(fmtCad(r.acbCad)) + '</td>' +
          '<td' + gainClass(r.gainCad) + '>' + esc(fmtCad(r.gainCad)) + '</td>' +
          '<td>' + flags.join(' ') + '</td>' +
          '</tr>';
      });
    }
    const totalRow =
      '<tr class="total">' +
      '<td>Totals</td><td></td><td></td>' +
      '<td class="num">' + esc(fmtCad(s.totalProceedsCad)) + '</td>' +
      '<td class="num">' + esc(fmtCad(s.totalAcbCad)) + '</td>' +
      '<td' + gainClass(s.totalGainCad) + '>' + esc(fmtCad(s.totalGainCad)) + '</td>' +
      '<td>' + (s.superficialCount ? '<span class="flag">' + esc(s.superficialCount) + ' superficial</span>' : '') + '</td>' +
      '</tr>';
    return (
      '<h2>Capital Dispositions (Schedule 3)</h2>' +
      '<p class="sub">Non-registered accounts only. Identical property pooled across your taxable accounts; proceeds net of commission, all figures in CAD at each trade\'s stored rate.</p>' +
      '<table><thead><tr>' +
      '<th>Security</th><th>Date</th><th class="num">Shares</th><th class="num">Proceeds (CAD)</th><th class="num">ACB (CAD)</th><th class="num">Gain / (Loss)</th><th>Flags</th>' +
      '</tr></thead><tbody>' + body + totalRow + '</tbody></table>'
    );
  }

  function renderIncome(inc) {
    const rows = (inc && inc.bySymbol) || [];
    let body = '';
    if (!rows.length) {
      body = '<tr><td colspan="2" style="color:#7A818E;padding:12px 8px;">No dividend or distribution income recorded for this year.</td></tr>';
    } else {
      rows.forEach(function (r) {
        body += '<tr><td>' + esc(r.symbol) + '</td><td class="num">' + esc(fmtCad(r.cad)) + '</td></tr>';
      });
    }
    body +=
      '<tr class="total"><td>Total investment income</td><td class="num">' +
      esc(fmtCad(inc && inc.grandTotalCad)) + '</td></tr>';
    return (
      '<h2>Investment Income</h2>' +
      '<p class="sub">Dividends and distributions recorded this year, grouped by security. Confirm eligible vs non-eligible status and any foreign withholding against your T3 and T5 slips.</p>' +
      '<table><thead><tr><th>Security</th><th class="num">Income (CAD)</th></tr></thead><tbody>' +
      body + '</tbody></table>'
    );
  }

  function renderReconciliation(recon) {
    const rows = Array.isArray(recon) ? recon : [];
    let body = '';
    if (!rows.length) {
      body = '<tr><td colspan="5" style="color:#7A818E;padding:12px 8px;">No dispositions to reconcile this year.</td></tr>';
    } else {
      rows.forEach(function (r) {
        body +=
          '<tr>' +
          '<td>' + esc(r.symbol) + '</td>' +
          '<td class="num">' + esc(fmtCad(r.trackerProceedsCad)) + '</td>' +
          '<td class="num">' + esc(fmtCad(r.trackerAcbCad)) + '</td>' +
          '<td' + gainClass(r.trackerGainCad) + '>' + esc(fmtCad(r.trackerGainCad)) + '</td>' +
          '<td class="blank">&nbsp;</td>' +
          '</tr>';
      });
    }
    return (
      '<h2>T5008 Reconciliation</h2>' +
      '<p class="sub">Your broker\'s T5008 cost or book value (box 20) is often their own average and frequently wrong. Enter it in the shaded column and compare to the tracker ACB before you accept the slip.</p>' +
      '<table><thead><tr>' +
      '<th>Security</th><th class="num">Tracker proceeds</th><th class="num">Tracker ACB</th><th class="num">Tracker gain / (loss)</th><th>Broker T5008 book value (enter)</th>' +
      '</tr></thead><tbody>' + body + '</tbody></table>'
    );
  }

  function renderTrueCost(tc) {
    if (!tc) return '';
    const cards = [];
    if (tc.currentBrokerCost != null) {
      cards.push('<div class="card"><div class="k">Your broker, per year</div><div class="v">' + esc(fmtCad(tc.currentBrokerCost)) + '</div></div>');
    }
    if (tc.cheapestBrokerCost != null) {
      cards.push('<div class="card"><div class="k">Cheapest venue' + (tc.cheapestBrokerName ? ' (' + esc(tc.cheapestBrokerName) + ')' : '') + '</div><div class="v">' + esc(fmtCad(tc.cheapestBrokerCost)) + '</div></div>');
    }
    if (tc.annualOverpayment != null) {
      cards.push('<div class="card hot"><div class="k">Annual overpayment</div><div class="v">' + esc(fmtCad(tc.annualOverpayment)) + '</div></div>');
    }
    if (tc.fxDrag != null) {
      cards.push('<div class="card"><div class="k">FX drag, per year</div><div class="v">' + esc(fmtCad(tc.fxDrag)) + '</div></div>');
    }
    return (
      '<h2>True Cost of Your Trading</h2>' +
      '<p class="sub">Modeled annual cost of your trading pattern versus the cheapest Canadian venue, from the Fee X-Ray. Estimates, not advice; verify each broker\'s current fee schedule.</p>' +
      '<div class="cards">' + cards.join('') + '</div>'
    );
  }

  function renderApprox(warnings) {
    const list = Array.isArray(warnings) ? warnings : [];
    let inner;
    if (!list.length) {
      inner = 'None. Every disposition above rests on entered trade history.';
    } else {
      inner =
        'These securities have at least one lot whose cost basis rests on an imported broker average or an estimated FX rate. Backfill real trade history before you file; the reported gain or loss for these names is not yet filing-grade.' +
        '<div class="chips">' + list.map(function (s) { return '<span class="chip">' + esc(s) + '</span>'; }).join('') + '</div>';
    }
    return (
      '<h2>Approximate cost basis - verify before filing</h2>' +
      '<div class="callout">' + inner + '</div>'
    );
  }

  function renderCaveats(caveats) {
    const list = Array.isArray(caveats) ? caveats : [];
    return (
      '<h2>What this does not know</h2>' +
      '<ul class="caveats">' + list.map(function (c) { return '<li>' + esc(c) + '</li>'; }).join('') + '</ul>'
    );
  }

  // renderTaxPackHtml(pack) -> print-ready HTML FRAGMENT (no <html>/<head>/<body>)
  function renderTaxPackHtml(pack) {
    pack = pack || {};
    const meta = pack.meta || {};
    const year = meta.year != null ? String(meta.year) : '';

    let html = '<div class="gsp-taxpack">';
    html += '<style>' + STYLE + '</style>';
    html += '<h1>' + esc(year) + ' Investment Tax Summary</h1>';
    html += '<p class="sub">Prepared by GSP Trading from your entered transactions. Educational working paper for you and your accountant.</p>';
    html += '<div class="disclaimer"><strong>Not tax advice. Not a T-slip.</strong><p>' + esc(meta.disclaimer || DISCLAIMER) + '</p></div>';
    html += renderSchedule3(pack.schedule3);
    html += renderIncome(pack.incomeSummary);
    html += renderReconciliation(pack.reconciliation);
    html += renderTrueCost(pack.trueCost);
    html += renderApprox(pack.approxWarnings);
    html += renderCaveats((meta.caveats && meta.caveats.length) ? meta.caveats : CAVEATS);
    html += '<div class="foot">GSP Trading tax pack. Figures are computed from your own entries and are not verified against any broker slip or CRA record. Review with a qualified tax professional before filing.</div>';
    html += '</div>';
    return html;
  }

  return {
    buildTaxPack: buildTaxPack,
    renderTaxPackHtml: renderTaxPackHtml,
    DISCLAIMER: DISCLAIMER,
    CAVEATS: CAVEATS.slice(),
  };
})();

if (typeof module !== 'undefined' && module.exports) {
  module.exports = TaxPack;
} else if (typeof window !== 'undefined') {
  window.TaxPack = TaxPack;
}
